#pragma once
#include <controllers/ilobby_store.hpp>
#include <match/match_instance.hpp>
#include <match/modload/artifacts.hpp>
#include <common/lobby.hpp>
#include <common/ws.hpp>
#include <http_router.hpp>
#include <atomic>
#include <random>
#include <string>
#include <unordered_map>
#include <vector>
#include <transport/iaction_router.hpp>
#include <transport/ibroadcaster.hpp>
#include <transport/itimer_service.hpp>
#include <transport/presence_registry.hpp>
#include <websocket_context.hpp>

/**
 * @file lobby_controller.hpp
 * @brief Definition of the controller for managing Lobbies. Handles all the I/O between
 * Client and Server regarding the initialization of Lobbies, and the start of game Matches,
 * to which it subsequently hands over control.
 */

/**
 * @class LobbyController
 * @brief Manages the in-memory state of all the active lobbies.
 * * This class does not use a database: the lobbies are ephemeral and live only
 * for the duration of the server session. It handles creation, joining,
 * temporary disconnections and reconnection of clients via WebSocket.
 */
class LobbyController : public ILobbyStore {
public:
    /**
     * @brief Constructor of the LobbyController.
     * Registers the WebSocket action handlers and starts the eviction timer.
     * @param router    WebSocket action router (DI seam).
     * @param broadcast Transport layer for sends/publishes (DI seam).
     * @param timers    Timer service for the eviction clock (DI seam).
     * @param presence  Connection registry, also indexes username -> lobby ID
     *                  (perf audit M-1, replaces the old O(N) member scan).
     * @param http_router Optional HTTP router; when non-null, registers the
     *                  `GET /api/decks` deck-catalog endpoint. Left null by
     *                  unit tests that do not exercise HTTP routing.
     * @param mods_root Optional mods folder used to resolve deck snapshots;
     *                  defaults to the `UNI_MODS_DIR` env var (or `mods`).
     */
    LobbyController(IActionRouter& router, IBroadcaster& broadcast,
                    ITimerService& timers, PresenceRegistry& presence,
                    HttpRouter* http_router = nullptr,
                    std::string mods_root = "");

    /**
     * @brief Destructor. Takes care of cleaning up the associated libuv timers.
     */
    ~LobbyController();

    /**
     * @brief Handler called when a client establishes a new WebSocket connection.
     * If the user was already in a lobby (reconnection scenario), it updates the socket
     * pointer and restores their presence.
     * * @param ws Pointer to the WebSocket socket.
     * @param sd Data associated with the socket (contains username, etc.).
     */
    void OnOpen(AppWebSocket* ws, PerSocketData* sd);

    /**
     * @brief Handler called when a client closes the connection.
     * Marks the member as disconnected and records the timestamp. Does not immediately remove
     * the user, but starts a grace period.
     * * @param ws Pointer to the disconnected WebSocket socket.
     * @param sd Data associated with the socket.
     */
    void OnClose(AppWebSocket* ws, PerSocketData* sd);

    /**
     * @brief Retrieves a pointer to a lobby by its invite code.
     * * @param code 6-character alphanumeric code (e.g. "XK4F9Z").
     * @return Lobby* Pointer to the lobby, or nullptr if not found.
     */
    Lobby* GetLobbyByCode(const std::string& code) {
        auto it = code_to_id_.find(code);
        if (it == code_to_id_.end()) return nullptr;
        auto jt = lobbies_.find(it->second);
        if (jt == lobbies_.end()) {
            code_to_id_.erase(it);
            return nullptr;
        }
        return &jt->second;
    }

    /**
     * @brief Retrieves a pointer to a lobby by its internal numeric ID.
     * * @param id Unique ID generated by the server.
     * @return Lobby* Pointer to the lobby, or nullptr if not found.
     */
    Lobby* GetLobbyById(uint32_t id) override {
        auto it = lobbies_.find(id);
        if (it != lobbies_.end()) {
            return &it->second;
        }
        return nullptr;
    }

    /**
     * @brief Registers a callback to execute when a match starts.
     * Multiple callbacks are supported; all are invoked in registration order.
     * @param callback The function to invoke.
     */
    void OnGameStarted(MatchStartedCallback callback) override {
        on_game_started_.push_back(std::move(callback));
    }

    /**
     * @brief Registers a callback to execute when a player is replaced.
     * Multiple callbacks are supported; all are invoked in registration order.
     * @param callback The function to invoke.
     */
    void OnPlayerReplaced(PlayerReplacedCallback callback) override {
        on_player_replaced_.push_back(std::move(callback));
    }

    /**
     * @brief Registers a callback invoked when a match is aborted due to disconnections.
     * The callback is responsible for sending the kMatchOver wire frame to the surviving player.
     * @param callback The function to invoke.
     */
    void OnMatchAborted(MatchAbortedCallback callback) override {
        on_match_aborted_.push_back(std::move(callback));
    }

    /**
     * @brief Registers a callback invoked once a lobby has no humans left
     * and is about to be destroyed.
     * Multiple callbacks are supported; all are invoked in registration order.
     * @param callback The function to invoke.
     */
    void OnLobbyDestroyed(LobbyDestroyedCallback callback) override {
        on_lobby_destroyed_.push_back(std::move(callback));
    }

    /**
     * @brief Tears down the match for the given lobby after a normal match-over.
     * Called by MatchController once all kMatchOver frames have been sent.
     * @param lobby_id ID of the lobby whose match to destroy.
     */
    void NotifyMatchOver(uint32_t lobby_id) override;

    /**
     * @brief Saves the current state of the match associated with the lobby to the database.
     * @param lobby Reference to the lobby whose state to save.
     */
    void SaveMatchStateToDB(Lobby& lobby);

    /**
     * @brief Counts the lobbies whose match is currently in progress (not finished).
     * Used by the deploy gate to avoid swapping the container mid-game.
     * @return std::size_t Number of active matches.
     */
    std::size_t ActiveMatchCount() const;

    /**
     * @brief Builds the `GET /api/decks` response body from a mods scan.
     * * Emits `{ "decks": [ {id, name, namespace, mods}, ... ] }`, one entry
     * per `decks/*.json` snapshot across every loaded mod. `id` is the local
     * deck id, `namespace` the owning mod and `mods` the deck's mod
     * requirements. Deterministic order: mods are sorted by
     * manifest id by the loader, decks by filename.
     * @param mods Every loaded mod, as returned by `ScanModsDirectory`.
     * @return nlohmann::json The response body.
     */
    static nlohmann::json DeckCatalogJson(
        const std::vector<match::modload::LoadedMod>& mods);

    /**
     * @brief Loads one deck snapshot (mod list + card multiset + typed
     * settings bag) into `settings.deck` atomically.
     * * Stores the schema-shaped object (`id`, `name`, `namespace`, `mods`,
     * `cards`, `settings`) verbatim; the new engine consumes it at the
     * controller. The legacy scalar settings are deliberately left alone so
     * freestyle editing remains fully additive during the coexistence phase.
     * @param settings Target lobby settings, mutated in place.
     * @param mods     Every loaded mod to search for `deck_id`.
     * @param deck_id  Full `namespace:id` (or bare local id) of the deck.
     * @return true when a matching deck was found and applied, false otherwise
     *         (settings left untouched).
     */
    static bool ApplyDeckSnapshot(
        LobbySettings& settings,
        const std::vector<match::modload::LoadedMod>& mods,
        const std::string& deck_id);

private:
    /**
     * @brief Verifies the integrity of the current match data (e.g. host realignment).
     * @param lobby The lobby to verify.
     */
    void CheckMatchIntegrity(Lobby& lobby);

    /**
     * @brief Handles the request to create a new lobby.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     */
    void HandleCreate(WsContext ctx, const json& msg);

    /**
     * @brief Handles the request to join a lobby via code.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     */
    void HandleJoin(WsContext ctx, const json& msg);

    /**
     * @brief Joins the caller to the fullest open public lobby with a free slot.
     * @param context Caller's socket/session context.
     * @param message Incoming lobby_quick_join payload.
     */
    void HandleQuickJoin(WsContext context, const nlohmann::json& message);

    /**
     * @brief Handles the request to reconnect to a lobby.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     */
    void HandleRejoin(WsContext ctx, const json& msg);

    /**
     * @brief Handles a user's voluntary departure from the lobby.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     */
    void HandleLeave(WsContext ctx, const json& msg);

    /**
     * @brief Handles the request for the list of active public lobbies.
     * Includes a derived `status` ("open"|"in-game"|"full"), the lobby's
     * `active_mods` and `allow_bot_takeover` so the client can filter/sort
     * without a dedicated query-param wire protocol.
     * @todo If browse filtering grows further (server-side query params,
     *       pagination), extract this into its own LobbyBrowseController.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     */
    void HandleList(WsContext ctx, const json& msg);

    /**
     * @brief Returns static server metadata (the rule catalog) to the client.
     * Fetched lazily once per session by the frontend catalog store instead of
     * being attached to every join/create/rejoin response.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     */
    void HandleGetMetadata(WsContext ctx, const json& msg);

    /**
     * @brief HTTP handler for `GET /api/decks`.
     * * Scans `mods_root_` and writes the deck catalog as JSON. Returns 500
     * with an `error` object when the mods folder cannot be scanned.
     * @param res Pointer to the HTTP response (uWS).
     */
    void HandleListDecks(AppResponse* res);

    /**
     * @brief Promotes a specific player to the Host role of the lobby.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     */
    void HandlePromote(WsContext ctx, const json& msg);

    /**
     * @brief Kicks a player from the lobby (only executable by the Host).
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     */
    void HandleKick(WsContext ctx, const json& msg);

    /**
     * @brief Updates the lobby settings (only executable by the Host).
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     */
    void HandleUpdateSettings(WsContext ctx, const json& msg);

    /**
     * @brief Starts the match for the current lobby. Initializes the game instance.
     * @param context WebSocket context of the request.
     * @param message Associated JSON payload.
     */
    void HandleStartGame(WsContext context, const nlohmann::json& message);

    /**
     * @brief Flips the caller's own ready state and broadcasts the updated lobby.
     * @param context Caller's socket/session context.
     * @param message Incoming lobby_toggle_ready payload.
     */
    void HandleToggleReady(WsContext context, const nlohmann::json& message);

    /**
     * @brief Updates the caller's streamer / privacy mode preference.
     * @param context Caller's socket/session context.
     * @param message Incoming user_update_privacy payload.
     */
    void HandleUserUpdatePrivacy(WsContext context, const nlohmann::json& message);

    /**
     * @brief Serializes the member list into JSON format for sending via WebSocket.
     * @param lobby The lobby whose members to serialize.
     * @return json JSON object representing the members.
     */
    static json MemberListJson(const Lobby& lobby);

    /**
     * @brief Broadcasts the `lobby_updated` event to all connected members.
     * @param lobby The lobby to broadcast from.
     */
    void BroadcastUpdate(const Lobby& lobby) const;

    /**
     * @brief Sends a `match_state_updated` frame to a single socket, including pending action
     * context when the engine is waiting for input from that player.
     */
    void SendMatchStateToSocket(const Lobby& lobby, AppWebSocket* ws, const std::string& username,
                                 uWS::OpCode op_code) const;

    /**
     * @brief Removes a member from the lobby. Destroys the lobby if it becomes empty.
     * @param lobby_id ID of the lobby.
     * @param username Username of the player to remove.
     * @param explicit_leave True if the user left voluntarily.
     * @param request_id ID of the request (optional, for tracking).
     * @param self_sd When the caller already holds the removed member's own
     * PerSocketData (e.g. HandleLeave, which dispatches on the leaver's own
     * connection), pass it here so this skips `socket->getUserData()` and
     * uses it directly instead. Left null for removals acting on someone
     * else's socket (kick, eviction), which still resolve it that way.
     * @return true if the lobby still exists, false if it was destroyed.
     */
    bool RemoveMember(uint32_t lobby_id, const std::string& username, bool explicit_leave = true,
                       const std::string& request_id = "", PerSocketData* self_sd = nullptr);

    /**
     * @brief Finds which lobby a given user currently belongs to.
     * @param username The username to look up.
     * @return Lobby* Pointer to the lobby, nullptr if not in any lobby.
     */
    Lobby* FindLobbyForUser(const std::string& username);

    /**< Multicast callbacks for match start. */
    std::vector<MatchStartedCallback>   on_game_started_;
    /**< Multicast callbacks for player replacement. */
    std::vector<PlayerReplacedCallback> on_player_replaced_;
    /**< Multicast callbacks for aborted matches (< 2 members). */
    std::vector<MatchAbortedCallback>   on_match_aborted_;
    /**< Multicast callbacks for lobby destruction. */
    std::vector<LobbyDestroyedCallback> on_lobby_destroyed_;

    IActionRouter& action_router_;  /**< Reference to the WS action router. */
    IBroadcaster&  broadcaster_;    /**< Transport layer for all sends/publishes. */
    ITimerService& timer_service_;  /**< Timer service for the eviction clock. */
    PresenceRegistry& presence_;    /**< Connection registry; also indexes username -> lobby ID. */
    /**< Mods folder scanned to resolve deck snapshots (env: UNI_MODS_DIR). */
    std::string mods_root_;

    std::unordered_map<uint32_t, Lobby> lobbies_;        /**< Primary storage of the lobbies. */
    std::unordered_map<std::string, uint32_t> code_to_id_; /**< Secondary index for fast lookup. */

    std::atomic<uint32_t> next_id_{1};          /**< Thread-safe counter for the lobby IDs. */
    /**< Grace period (ms) before eviction (env: RECONNECT_GRACE_MS). */
    int reconnect_grace_ms_ = 1'000 * 30;
    /**< Absolute upper bound on LobbySettings::max_players across all lobbies
     * (env: ABSOLUTE_MAX_LOBBY_MEMBERS), clamped to contract::kMaxLobbyMembers. */
    int absolute_max_lobby_members_ = contract::kMaxLobbyMembers;
    std::mt19937 rng_{std::random_device {}()};  /**< Shared RNG for bot name selection. */
};
