#pragma once
#include <functional>
#include <memory>
#include <string>
#include <string_view>
#include <algorithm>
#ifndef _WIN32
#include <arpa/inet.h>
#endif
#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <nlohmann/json.hpp>
#include <common/env.hpp>
#include <websocket_context.hpp>

/**
 * @file http.hpp
 * @brief Utility functions for handling the HTTP protocol.
 * * Since uWebSockets uses a non-blocking, event-driven architecture,
 * this file contains crucial helpers to simplify the safe extraction
 * of chunked bodies and the parsing of headers (e.g. Cookies).
 */

namespace http {

/**
 * @brief Asynchronously accumulates an entire chunked HTTP body from uWebSockets.
 * * Since uWebSockets is non-blocking, bodies arrive in one or more `string_view` chunks
 * via the `onData` callback. The `isLast` boolean parameter signals the last chunk.
 * This function buffers the chunks on its own and acts only when the transfer is complete.
 * * @details Implements an `is_alive` memory guard (`std::shared_ptr<bool>`) to handle sudden
 * disconnections. If the client interrupts the transfer, uWS calls `onAborted`. The guard becomes `false`,
 * preventing subsequent `onData` triggers from accessing the now-dangling `res` pointer.
 * * @param res Pointer to the Response object of the current HTTP request. Must remain valid until completion.
 * @param max_bytes Hard cap in bytes to avoid DDoS attacks. If exceeded, returns 413.
 * @param callback The function to invoke, exactly once, with the complete body string (if not aborted).
 */
inline void ReadBody(AppResponse* res, size_t max_bytes,
                      std::function<void(const std::string&)> callback) {
    auto is_alive = std::make_shared<bool>(true);
    auto buffer   = std::make_shared<std::string>();

    res->onAborted([is_alive] { *is_alive = false; });

    res->onData([is_alive, buffer, max_bytes, callback = std::move(callback), res](
                    std::string_view chunk, bool isLast) mutable {
        if (!*is_alive) return;

        buffer->append(chunk.data(), chunk.size());

        if (buffer->size() > max_bytes) {
            // INFO: Stop receiving before responding: leaving is_alive true
            //       lets uWS keep delivering chunks into an abandoned buffer
            //       and can double-end the response.
            *is_alive = false;
            res->writeStatus("413 Payload Too Large")->end();
            return;
        }

        if (!isLast) return;
        try {
            callback(*buffer);
        } catch (const nlohmann::json::exception&) {
            // INFO: Wrong-typed JSON field (value() throws type_error) must
            // not unwind into uWS; answer 400 instead of terminating.
            *is_alive = false;
            res->writeStatus("400 Bad Request")->end();
        }
    });
}

/**
 * @brief Removes ASCII whitespace (spaces, tabs, newlines) from the beginning and end of a string.
 * Being `constexpr`, if evaluated at compile time it generates no overhead.
 * * @param str The view of the original string.
 * @return std::string_view A centred portion of the string free of the outer whitespace. Returns an empty view if composed solely of whitespace.
 */
constexpr std::string_view TrimWhitespace(std::string_view str) {
    size_t first = str.find_first_not_of(" \t\r\n");
    if (first == std::string_view::npos) {
        return {};
    }
    size_t last = str.find_last_not_of(" \t\r\n");
    return str.substr(first, (last - first + 1));
}

/**
 * @brief Safely extracts the value of a single cookie from the raw header string.
 * * Iteratively scans the `Cookie` header string (e.g. `session=123; user=abc`),
 * splitting the pairs at the semicolon and looking for the exact key match,
 * cleaning up any whitespace generated by the browser.
 * * @param cookie_header The native HTTP header string containing the cookies.
 * @param target_key The identifying key of the cookie to search for.
 * @return std::optional<std::string> The decoded cookie value, or an empty string if the key does not exist.
 */
inline std::optional<std::string> GetCookieValue(std::string_view cookie_header,
                                                  std::string_view target_key) {
    size_t start = 0;

    while (start < cookie_header.size()) {
        size_t end = cookie_header.find(';', start);

        std::string_view pair = (end == std::string_view::npos)
                                ? cookie_header.substr(start)
                                : cookie_header.substr(start, end - start);

        // Split the pair into Key and Value
        size_t eq_pos = pair.find('=');
        if (eq_pos != std::string_view::npos) {
            std::string_view key = TrimWhitespace(pair.substr(0, eq_pos));

            if (key == target_key) {
                return std::string(TrimWhitespace(pair.substr(eq_pos + 1)));
            }
        }

        if (end == std::string_view::npos) {
            break;
        }

        start = end + 1;
    }

    return "";
}

/**
 * @brief Unwraps an IPv4-mapped IPv6 address ("::ffff:1.2.3.4") to plain IPv4
 * ("1.2.3.4"). uWebSockets binds dual-stack sockets, so `getRemoteAddressAsText()`
 * reports IPv4 clients in this mapped form; logs and rate-limit keys read far more
 * usefully as plain IPv4. Genuine IPv6 addresses (and anything else) pass through
 * untouched.
 */
constexpr std::string_view UnwrapIpv4MappedIpv6(std::string_view ip) {
    constexpr std::string_view kPrefix = "::ffff:";
    if (ip.substr(0, kPrefix.size()) == kPrefix) {
        return ip.substr(kPrefix.size());
    }
    return ip;
}

#ifndef _WIN32
/**
 * @brief True when `ip` is inside IPv4 `prefix/len`. IPv6 is treated as
 * untrusted (the deploy proxy is IPv4 on the docker network); unknown input,
 * malformed CIDRs and non-IPv4 addresses return false.
 */
inline bool IpInIpv4Cidr(std::string_view ip, std::string_view cidr) {
    const auto slash = cidr.find('/');
    int bits = 32;
    if (slash != std::string_view::npos) {
        const std::string_view len = TrimWhitespace(cidr.substr(slash + 1));
        // INFO: Fail closed on a malformed prefix. Only a non-empty run of
        //       ASCII digits is accepted; the old std::atoi path turned
        //       ""/"x"/-1 into 0 and then trusted every peer.
        if (len.empty() ||
            !std::all_of(len.begin(), len.end(), [](unsigned char c) {
                return std::isdigit(c) != 0;
            })) {
            return false;
        }
        // Bounded parse: saturate above /32 so no shift sees an out-of-range
        // prefix length (also avoids std::atoi overflow on absurd input).
        bits = 0;
        for (const char c : len) {
            bits = bits * 10 + (c - '0');
            if (bits > 32) {
                bits = 32;
                break;
            }
        }
    }
    const std::string net(cidr.substr(0, slash));
    struct in_addr a{}, b{};
    if (inet_pton(AF_INET, std::string(ip).c_str(), &a) != 1) return false;
    if (inet_pton(AF_INET, net.c_str(), &b) != 1) return false;
    if (bits == 0) return true;  // /0 intentionally matches the whole space
    if (bits > 32) bits = 32;
    const uint32_t mask = bits == 32 ? 0xFFFFFFFFu : ~((1u << (32 - bits)) - 1u);
    return (ntohl(a.s_addr) & mask) == (ntohl(b.s_addr) & mask);
}

/**
 * @brief Resolve the client IP, honouring XFF only from a trusted proxy.
 *
 * `peer_ip` is the direct socket peer (Traefik's container IP). The
 * `X-Forwarded-For` header is honoured only when that peer falls inside one of
 * the comma-separated `trusted_cidrs` (e.g. "172.16.0.0/12"); otherwise the
 * header is client-supplied and spoofable, so the peer address is returned.
 *
 * @param peer_ip Direct socket peer address.
 * @param xff Raw `X-Forwarded-For` value (empty when absent/untrusted).
 * @param trusted_cidrs Comma-separated proxy CIDR allowlist.
 * @return std::string The resolved client IP, always plain IPv4 when possible.
 */
inline std::string ResolveClientIp(std::string_view peer_ip, std::string_view xff,
                                   std::string_view trusted_cidrs) {
    // INFO: uWS on a dual-stack listener reports IPv4 peers in IPv4-mapped
    //       form (::ffff:172.x.y.z), which inet_pton(AF_INET) rejects.
    //       Normalise once so the CIDR check and fallback see plain IPv4.
    const std::string_view peer = UnwrapIpv4MappedIpv6(peer_ip);
    if (!xff.empty() && !trusted_cidrs.empty()) {
        std::size_t start = 0;
        while (start <= trusted_cidrs.size()) {
            const auto comma = trusted_cidrs.find(',', start);
            auto item = TrimWhitespace(trusted_cidrs.substr(
                start, comma == std::string_view::npos ? std::string_view::npos
                                                       : comma - start));
            if (!item.empty() && IpInIpv4Cidr(peer, item)) {
                const auto pos = xff.rfind(',');
                return std::string(UnwrapIpv4MappedIpv6(
                    TrimWhitespace(xff.substr(pos == std::string_view::npos ? 0 : pos + 1))));
            }
            if (comma == std::string_view::npos) break;
            start = comma + 1;
        }
    }
    return std::string(peer);
}
#endif  // !_WIN32

/**
 * @brief Resolve the originating client IP for rate-limiting / logging.
 *
 * Behind a trusted proxy (e.g. Traefik) `X-Forwarded-For`'s **right-most**
 * entry is the address the proxy actually observed; entries to its left are
 * client-supplied and spoofable. The header is honoured only when the socket
 * peer is inside `TRUSTED_PROXY_CIDRS` (comma list), so a direct connection can
 * never spoof its own IP. When `trust_proxy` is false, the header is absent, or
 * the peer is not a trusted proxy, the socket peer address is used.
 *
 * @param res Response, used for the socket peer address fallback.
 * @param req Request, source of the `X-Forwarded-For` header.
 * @param trust_proxy Whether to consider `X-Forwarded-For` at all.
 * @return std::string The resolved client IP (may be empty if unavailable). IPv4
 * clients are always reported as plain IPv4, never IPv4-mapped IPv6.
 */
inline std::string GetClientIp(AppResponse* res, AppRequest* req, bool trust_proxy) {
    const std::string_view peer = res->getRemoteAddressAsText();
#ifndef _WIN32
    const std::string_view xff =
        trust_proxy ? req->getHeader("x-forwarded-for") : std::string_view{};
    return ResolveClientIp(peer, xff, Env::Get("TRUSTED_PROXY_CIDRS", ""));
#else
    (void)trust_proxy;
    (void)req;
    return std::string(UnwrapIpv4MappedIpv6(peer));
#endif
}

}
